###

POST http://localhost:8080/media/bytes
Content-Type: image/jpeg

< Russian_passport.jpg

###

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="Russian_passport.jpg"
Content-Type: image/jpeg

< Russian_passport.jpg
--WebBoundary--

###

POST http://localhost:8080/media/verification
Content-Type: verification/form-data; boundary=WebBoundary


###

GET http://localhost:8080/orders/getAll

###

GET http://localhost:8080/orders/getById?id=2

###

GET http://localhost:8080/orders/getById?id=222

###

POST http://localhost:8080/orders/save
Content-Type: application/json

{
  "id" : 1,
  "salesman" : "Misha",
  "price" : 3700000,
  "bitcoin" : 2,
  "review" : 5,
  "min_amount" : 100,
  "max_amount" : 5000,
  "successful_deals" : 15,
  "status" : "online",
  "proStatus" : "no"
}

###

POST http://localhost:8080/orders/removeById?id=1

###

POST http://localhost:8080/deals/register
Content-Type: application/json

{
  "deal_id": 1,
  "name": "Andrey",
  "price": 10000,
  "balance_btc": 1.1,
  "rating": 4.8,
  "dealStatus": "buy"
}
