name: CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: maven build
        run: mvn -B package
      - name: upload jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/final-1.0.jar